### ISSUE TITLE
rename analyzed fork

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#101]
We fogot to modify this.
![image](https://user-images.githubusercontent.com/8794646/34269529-a993e268-e652-11e7-8d87-8ea784a31ef5.png)
Analyzed Forks --> Forks that have unmerged code ?

**Comment by FancyCoder0** [comment]
done.

**Comment by wasowski** [comment]
What happens if more than one programming language is used in a project?

Forks Number on GitHub -> should be "Forked on GitHub:" (Number is used only in this entry, so labels are not consistent).

"Forks containing unmerged code" would be slightly better (avoiding "that" which turns the label into almost a sentence). But this is of marginal importance.

**Comment by FancyCoder0** [comment]
Hi, Andrzej.

The programming language is just using Github API, and I don't know the mechanism github use to define the language of repo.

**Comment by wasowski** [comment]
OK. So the programming language is just information, means nothing for us. Then ignore that comment. The other labels could still be improved.

I am not sure that I understand your question.  But if you don't see my info on http://forks-insight.com/welcome there is a good reason for that: I have not logged in yet.  I am trying to catch up with issues.

**Comment by FancyCoder0** [comment]
ok, I see :)
